# Generated by Django 3.2 on 2025-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20251218_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoofingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='liveness_verified',
        ),
    ]
