# Generated by Django 3.2 on 2026-01-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_shift_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.shift')),
            ],
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['employee', 'date'], name='employees_e_employe_0193fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['date'], name='employees_e_date_0147b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeshiftschedule',
            unique_together={('employee', 'date')},
        ),
    ]
