# Generated by Django 3.2 on 2026-02-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20260130_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
