# Generated by Django 3.2 on 2026-02-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_register_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
