# Generated by Django 3.2 on 2026-02-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_register_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
