# Generated by Django 3.2 on 2026-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_register_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
