# Generated by Django 3.2 on 2026-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_register_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'OPD Kiosk 1'", max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='fingerprint_id',
        ),
        migrations.AddField(
            model_name='register',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
