# Generated by Django 3.2 on 2026-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20260310_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweddevice',
            name='ip_address',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='allowed_ip',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
