# Generated by Django 3.2 on 2026-03-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20260310_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddevice',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
