# Generated by Django 3.2 on 2026-07-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_auto_20260327_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
