# Generated by Django 3.2 on 2026-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_register_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMismatchLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified_employee_id', models.CharField(max_length=50)),
                ('mark_employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField()),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
