# Generated by Django 3.2 on 2026-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_facemismatchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoofingattempt',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
