# Generated by Django 3.2 on 2026-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='allowed_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
