# Generated by Django 3.2 on 2026-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_alter_register_allowed_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
