# Generated by Django 3.2 on 2026-07-27 08:17

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_auto_20260725_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.IntegerField(default=employees.models.generate_leave_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
