# Generated by Django 3.2 on 2026-08-27 04:02

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_auto_20260727_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tea', max_length=100)),
                ('code', models.CharField(default='TEA', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanteenQuotaRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_daily_quota', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanteenTokenIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.CharField(max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(default='Tea', max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'ISSUED'), ('REDEEMED', 'REDEEMED'), ('CANCELLED', 'CANCELLED')], default='ISSUED', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='id',
            field=models.IntegerField(default=employees.models.generate_leavetype_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
