# Generated by Django 3.2 on 2026-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_auto_20260827_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteentokenissue',
            name='reprint_count',
            field=models.IntegerField(default=0),
        ),
    ]
