# Generated by Django 3.2 on 2026-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_canteentokenissue_reprint_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('leave', 'Leave Update'), ('shift', 'Shift Roster'), ('canteen', 'Canteen Token'), ('announcement', 'Announcement'), ('general', 'General Alert')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
