# Generated by Django 3.2 on 2026-08-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweddevice',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alloweddevice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alloweddevice',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alloweddevice',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteenitem',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='canteenquotarule',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteenquotarule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='canteenquotarule',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteenquotarule',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='canteentokenissue',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteentokenissue',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='canteentokenissue',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='canteentokenissue',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.CharField(blank=True, help_text='User ID/Name who created this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='lastmodified_by',
            field=models.CharField(blank=True, help_text='User ID/Name who last modified this record', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='lastmodified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
