# Generated by Django 3.2 on 2026-08-28 07:19

import bson.objectid
from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_auto_20260828_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_groups',
            fields=[
                ('email', models.EmailField(max_length=500, unique=True)),
                ('employee_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('id', employees.models.ObjectIdField(default=bson.objectid.ObjectId, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GridFSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='system', max_length=100)),
            ],
            options={
                'db_table': 'gridfs_files',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('employeeId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('employeeName', models.CharField(max_length=255)),
                ('fatherName', models.CharField(blank=True, max_length=255, null=True)),
                ('motherName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('guardianNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('dateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryRole', models.CharField(default='Employee', max_length=100)),
                ('additionalRoles', models.JSONField(default=list)),
                ('dataEntitlements', models.JSONField(default=list)),
                ('hospitalCode', models.CharField(default='SH001', max_length=100)),
                ('employmentStatus', models.CharField(default='Active', max_length=20)),
                ('registrationNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('validityDate', models.DateField(blank=True, null=True)),
                ('kycDetails', models.JSONField(default=dict)),
                ('familyDetails', models.JSONField(default=dict)),
                ('qualifications', models.JSONField(default=list)),
                ('experiences', models.JSONField(default=list)),
                ('bankDetails', models.JSONField(default=dict)),
                ('salaryDetails', models.JSONField(default=dict)),
                ('fnfStatus', models.JSONField(default=dict)),
                ('profileImage', models.CharField(blank=True, max_length=255, null=True)),
                ('signatureFileId', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('employeeId', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('lastmodified_by', models.CharField(default='system', max_length=100)),
                ('lastmodified_date', models.DateTimeField(auto_now=True)),
                ('is_password_set', models.BooleanField(default=False)),
                ('role', models.CharField(default='Employee', max_length=100)),
            ],
        ),
    ]
