# Generated by Django 3.2 on 2026-10-06 04:59

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_admin_groups_gridfsfile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='avp_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='avp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='avp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='avp_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='avp_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='incharge_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='incharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='incharge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='incharge_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='incharge_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='assigned_departments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='assigned_wards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='parent_approver_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='supervising_hod_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='supervising_incharge_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='id',
            field=models.IntegerField(default=employees.models.generate_shiftschedule_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeeshiftschedule',
            name='lastmodified_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='profile',
                    table='backend_diagnostics_profile',
                ),
                migrations.AlterModelTable(
                    name='user',
                    table='backend_diagnostics_user',
                ),
            ]
        ),
    ]
